_target_: navsim.agents.recogdrive.recogdrive_agent.ReCogDriveAgent
_convert_: 'all'

trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  time_horizon: 4
  interval_length: 0.5
checkpoint_path: ''
vlm_path: ''
cam_type: 'single'
vlm_type: 'internvl'
dit_type: 'small'
sampling_method: 'ddim'
cache_mode: False
cache_hidden_state: True
metric_cache_path: ''
reference_policy_checkpoint: ''
vlm_size: 'large'
grpo: False
lr: 1e-4