hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common 
  job:
    chdir: False

cache_path: ${oc.env:NAVSIM_EXP_ROOT}/training_cache_transfuser
use_cache_without_dataset: false # load the training samples from the cache. scene-filter will be ignored
force_cache_computation: true

defaults:
  - default_common
  - default_evaluation
  - default_scoring_parameters
  - agent: constant_velocity_agent
  - _self_
  - override train_test_split: navtest

metric_cache_path: ${oc.env:NAVSIM_EXP_ROOT}/metric_cache # path to metric cache